version: '3.3'

services:
  web-app:
    container_name: web-app
    build: ./web-app
    image: web-app
    depends_on:
      - database-app
      - securityDB
    ports:
      - "8001:8001"

  database-app:
    container_name: data_base-app
    build: ./data_base-app
    image: data_base-app
    depends_on:
      - databaseDB
    ports:
      - "8003:8003"

  databaseDB:
    container_name: database
    image: postgres:13.2
    env_file:
      - ./data_base-db/database.env
    volumes:
      - ./data_base-db/data.sql:/docker-entrypoint-initdb.d/data.sql
      - ./data_base-db/data:/var/lib/postgresql/data/
    ports:
      - "5438:5432"

  securityDB:
    container_name: secur
    image: postgres:13.2
    env_file:
      - ./web-db/database.env
    volumes:
      - ./web-db/security.sql:/docker-entrypoint-initdb.d/security.sql
      - ./web-db/data:/var/lib/postgresql/data/
    ports:
      - "5439:5432"

