server:
  port: 8001
  servlet:
    context-path: /web-app
spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  datasource:
    data: classpath:security.sql
    url: jdbc:h2:mem:webdb
    driver-class-name: org.h2.Driver
    username: pass
    password: pass


